symfony_app/src/Entity/RegTrans.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RegTransRepository")
 */
class RegTrans
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type_transaction;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cyclicity;

    /**
     * @ORM\Column(type="integer")
     */
    private $day;

    /**
     * @ORM\Column(type="integer")
     */
    private $amount;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="integer")
     */
    private $user_id;

    /**
     * @ORM\Column(type="boolean")
     */
    private $show_on_home_page;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTypeTransaction(): ?string
    {
        return $this->type_transaction;
    }

    public function setTypeTransaction(string $type_transaction): self
    {
        $this->type_transaction = $type_transaction;

        return $this;
    }

    public function getCyclicity(): ?string
    {
        return $this->cyclicity;
    }

    public function setCyclicity(string $cyclicity): self
    {
        $this->cyclicity = $cyclicity;

        return $this;
    }

    public function getDay(): ?int
    {
        return $this->day;
    }

    public function setDay(int $day): self
    {
        $this->day = $day;

        return $this;
    }

    public function getAmount(): ?int
    {
        return $this->amount;
    }

    public function setAmount(int $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getShowOnHomePage(): ?bool
    {
        return $this->show_on_home_page;
    }

    public function setShowOnHomePage(bool $show_on_home_page): self
    {
        $this->show_on_home_page = $show_on_home_page;

        return $this;
    }
}

symfony_app/src/Controller/RegTransController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\RegTrans;
use App\Entity\Budget;

class RegTransController extends AbstractController
{
    /**
     * @Route("/regtrans")
     */
    public function index()
    {
        $user = $this->getUser();

        $budget = $this->getDoctrine()
            ->getRepository(Budget::class)
            ->findOneBy(['user_id' => $user->getId()]);
        $incomes = $this->getDoctrine()
            ->getRepository(RegTrans::class)
            ->findBy([
                'user_id' => $user->getId(),
                'type_transaction' => 'incomes',
            ]);
        $expenses = $this->getDoctrine()
            ->getRepository(RegTrans::class)
            ->findBy([
                'user_id' => $user->getId(),
                'type_transaction' => 'expenses',
            ]);

        return $this->render('regtrans/index.html.twig', [
            'user' => $user,
            'budget' => $budget,
            'incomes' => $incomes,
            'expenses' => $expenses,
        ]);
    }
}

symfony_app/templates/regtrans/index.html.twig
{% extends 'login.html.twig' %}
{% block title %}Regular transactions{% endblock %}
{% block body %}
<div class="card">
    <div class="card-body">
        {% for i in 1..2 %}
            {% if (incomes[0] is defined and expenses[0] is defined) %}

                {% if (i == 1) %}
                    {% set transactions = incomes %}
                {% else %}
                    {% set transactions = expenses %}
                {% endif %}
                <table class="table table-sm table-hover table-bordered" data-typetransactions="{{ transactions[0].typeTransaction }}">
                    <thead>
                        <tr class="b-pr">
                            <th colspan="6">
                                <p class="m-0 text-center">
                                    {% if (i == 1) %}
                                        Incomes
                                    {% else %}
                                        Expenses
                                    {% endif %}
                                </p>
                            </th>
                        </tr>
                        <tr>
                            <th>Cyclicity</th>
                            <th>Day</th>
                            <th>Amount</th>
                            <th>Description</th>
                            <th>Show on homepage</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in transactions %}
                            <tr data-row="{{ item.id }}">
                                <td data-column="cyclicity">
                                    {{ item.cyclicity }}
                                </td>
                                <td data-column="day">
                                    {{ item.day }}
                                </td>
                                <td data-column="amount">
                                    {{ item.amount }}
                                </td>
                                <td data-column="description">
                                    {{ item.description }}
                                </td>
                                <td data-column="show-on-homepage">
                                    {% if (item.showOnHomePage) %}
                                        yes
                                    {% else %}
                                        no
                                    {% endif %}
                                </td>
                                <td data-column="actions">
                                    <button type="button" class="btn btn-outline-danger btn-sm remove w-100">Remove</button>
                                </td>
                            </tr>
                        {% endfor %}
                        <tr data-row="input">
                            <td data-column="cyclicity">
                                <select class="form-control form-control-sm">
                                    <option selected="selected">e_month</option>
                                    <option>e_week</option>
                                    <option>e_day</option>
                                </select>
                            </td>
                            <td data-column="day" class="col-1">
                                <input class="form-control form-control-sm" type="text">
                                <span class="hidden default-eday">each</span>
                            </td>
                            <td data-column="amount">
                                <input class="form-control form-control-sm" type="text">
                            </td>
                            <td data-column="description">
                                <input class="form-control form-control-sm" type="text">
                            </td>
                            <td data-column="show-on-homepage">
                                <select class="form-control form-control-sm">
                                    <option selected="selected">no</option>
                                    <option>yes</option>
                                </select>
                            </td>
                            <td data-column="actions">
                                <button type="button" class="btn btn-outline-success btn-sm add w-100">Add</button>
                            </td>
                        </tr>
                        <tr data-row="error-wrapper">
                            <td colspan="6" class="table-danger p-0"></td>
                        </tr>
                    </tbody>
                </table>

            {% else %}

                {% if (i == 1) %}
                    {% set transactions = 'incomes' %}
                {% else %}
                    {% set transactions = 'expenses' %}
                {% endif %}
                <table class="table table-sm table-bordered" data-typetransactions="{{ transactions }}">
                    <thead>
                        <tr class="b-pr">
                            <th colspan="6">
                                <p class="m-0 text-center">
                                    {{ transactions }}
                                </p>
                            </th>
                        </tr>
                        <tr>
                            <th>Cyclicity</th>
                            <th>Day</th>
                            <th>Amount</th>
                            <th>Description</th>
                            <th>Show on homepage</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr data-row="input">
                            <td data-column="cyclicity">
                                <select class="form-control form-control-sm">
                                    <option selected="selected">e_month</option>
                                    <option>e_week</option>
                                    <option>e_day</option>
                                </select>
                            </td>
                            <td data-column="day" class="col-1">
                                <input class="form-control form-control-sm" type="text">
                                <span class="hidden default-eday">each</span>
                            </td>
                            <td data-column="amount">
                                <input class="form-control form-control-sm" type="text">
                            </td>
                            <td data-column="description">
                                <input class="form-control form-control-sm" type="text">
                            </td>
                            <td data-column="show-on-homepage">
                                <select class="form-control form-control-sm">
                                    <option selected="selected">no</option>
                                    <option>yes</option>
                                </select>
                            </td>
                            <td data-column="actions">
                                <button type="button" class="btn btn-outline-success btn-sm add w-100">Add</button>
                            </td>
                        </tr>
                        <tr data-row="error-wrapper">
                            <td colspan="6" class="table-danger p-0"></td>
                        </tr>
                    </tbody>
                </table>

            {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock%}