symfony_app/src/Entity/Hronos.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\HronosRepository")
 */
class Hronos
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $user_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $date;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $tih_fct;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $tih_teo;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $free_money;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $hl;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getDate(): ?string
    {
        return $this->date;
    }

    public function setDate(string $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getTihFct(): ?int
    {
        return $this->tih_fct;
    }

    public function setTihFct(?int $tih_fct): self
    {
        $this->tih_fct = $tih_fct;

        return $this;
    }

    public function getTihTeo(): ?int
    {
        return $this->tih_teo;
    }

    public function setTihTeo(?int $tih_teo): self
    {
        $this->tih_teo = $tih_teo;

        return $this;
    }

    public function getFreeMoney(): ?int
    {
        return $this->free_money;
    }

    public function setFreeMoney(?int $free_money): self
    {
        $this->free_money = $free_money;

        return $this;
    }

    public function getHl(): ?int
    {
        return $this->hl;
    }

    public function setHl(?int $hl): self
    {
        $this->hl = $hl;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

symfony_app/src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\RegTrans;
use App\Entity\Budget;
use Symfony\Component\Validator\Constraints\DateTime;
use App\Vendor\Hronos\Hronos;
use App\Vendor\TeoBudget\TeoBudget;

class HomeController extends AbstractController
{
    /**
     * @Route("/")
     */
    public function index()
    {
        $user = $this->getUser();

        $budget = $this->getDoctrine()
            ->getRepository(Budget::class)
            ->findOneBy(['user_id' => $user->getId()]);

        if (!$budget) {
            return $this->render('start/index.html.twig', [
                'user' => $user,
            ]);
        }

        $regTrans = $this->getDoctrine()
            ->getRepository(RegTrans::class)
            ->findBy(['user_id' => $user->getId()]);

        $hronos = new Hronos($budget, $regTrans);
        $teoBudget = new TeoBudget($regTrans);

        return $this->render('home/index.html.twig', [
            'user' => $user,
            'budget' => $budget,
            'hronos' => $hronos,
            'teoBudget' => $teoBudget,
        ]);
    }
}

symfony_app/templates/home/budget.html.twig
<table class="table table-sm table-bordered table-hover">
    <thead>
        <tr class="b-pr">
            <th colspan="2"><p class="m-0 text-center">Budget now</p></th>
        </tr>
        <tr>
            <th></th>
            <th>Amount</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td data-row="1">
                Turn
            </td>
            <td data-row="1">
                <div class="d-flex justify-content-between">
                    <div class="d-flex align-items-center">
                        <span class="amount">
                            {{ budget.tih }}
                        </span>
                        <input class="form-control form-control-sm hidden tih" type="text" value="{{ budget.tih }}"/>
                    </div>
                    <div class="d-flex align-items-center">
                        <button type="button" class="btn btn-outline-warning btn-sm budget-edit">Edit</button>
                        <button type="button" class="btn btn-outline-danger btn-sm hidden budget-cancel mx-2">Cancel</button>
                        <button type="button" class="btn btn-outline-success btn-sm hidden budget-submit">Submit</button>
                    </div>
                </div>
            </td>
        </tr>
        <tr>
            <td data-row="2">
                Reserve
            </td>
            <td data-row="2">
                <div class="d-flex justify-content-between">
                    <div class="d-flex align-items-center">
                        <span class="amount c-success">
                            {{ budget.hl }}
                        </span>
                        <input class="form-control form-control-sm hidden hl" type="text" value="{{ budget.hl }}"/>
                    </div>
                    <div class="d-flex align-items-center">
                        <button type="button" class="btn btn-outline-warning btn-sm budget-edit">Edit</button>
                        <button type="button" class="btn btn-outline-danger btn-sm hidden budget-cancel mx-2">Cancel</button>
                        <button type="button" class="btn btn-outline-success btn-sm hidden budget-submit">Submit</button>
                    </div>
                </div>
            </td>
        </tr>
        <tr>
            <td data-row="3">
                Free money
            </td>
            <td data-row="3">
                <div class="d-flex justify-content-between">
                    <span class="c-{{ hronos.maxCritDay.typeCrit }}">
                        {{ hronos.freeMoney }}
                    </span>
                    next: {{ hronos.maxCritDay.currentUnixTime|date('d.m') }}
                </div>
            </td>
        </tr>
    </tbody>
</table>

symfony_app/templates/home/conclusion.html.twig
<table class="table table-sm table-bordered">
    <!-- {{ dump(hronos.criticallyDaysRender) }} -->
    <thead>
        <tr class="b-pr">
            <th colspan="4"><p class="m-0 text-center">Conclusion 1 month</p></th>
        </tr>
        <tr>
            <th></th>
            <th>Date</th>
            <th>Turn</th>
            <th>Reserve</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Start</td>
            <td>{{ hronos.startUnixTime|date('d.m') }}</td>
            <td>{{ hronos.startTih }}</td>
            <td>{{ hronos.startHl }}</td>
        </tr>
        {% set row = 1 %}
        {% for critically in hronos.criticallyDaysRender %}
            <tr>
                {% if loop.first %}
                    <td rowspan="{{ hronos.criticallyDaysRender|length }}"
                        data-row="{{ row }}">
                        Crit
                    </td>
                {% endif %}
                <td data-row="{{ row }}"
                    class="table-{{ critically.typeCrit }}">
                        {{ critically.currentUnixTime|date('d.m') }}
                </td>
                <td class="table-{{ critically.typeCrit }}"
                    colspan="2"
                    data-row="{{ row }}">
                        {{ critically.summary }}
                </td>
            </tr>
            {% set row = row + 1 %}
        {% endfor %}
        <tr>
            <td>End</td>
            <td>{{ hronos.endUnixTime|date('d.m') }}</td>
            <td>{{ hronos.endTih }}</td>
            <td>{{ hronos.endHl }}</td>
        </tr>
        <tr>
            <td>Max crit</td>
            <td class="table-{{ hronos.maxCritDay.typeCrit }}">
                {{ hronos.maxCritDay.currentUnixTime|date('d.m') }}
            </td>
            <td colspan="2" class="table-{{ hronos.maxCritDay.typeCrit }}">
                {{ hronos.maxCritDay.summary }}
            </td>
        </tr>
    </tbody>
</table>

symfony_app/templates/home/index.html.twig
{% extends 'login.html.twig' %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="card w-100">
    <div class="row m-3">
        <div class="col-sm p-1">
            {% include 'home/budget.html.twig' %}
        </div>
        <div class="col-sm p-1">
            {% include 'home/conclusion.html.twig' %}
        </div>
        <div class="col-sm p-1">
            {% include 'home/teo-budget.html.twig' %}
        </div>
    </div>
</div>
{% endblock %}

symfony_app/templates/home/teo-budget.html.twig
<table class="table table-sm table-bordered">
    <thead>
        <tr class="b-pr">
            <th colspan="3"><p class="m-0 text-center">Teo budget</p></th>
        </tr>
        <tr>
            <th></th>
            <th>Turn</th>
            <th>Reserve</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Incomes</td>
            <td class="c-success">+{{ teoBudget.incomes }}</td>
            <td class="success">+{{ teoBudget.reserve }}</td>
        </tr>
        <tr>
            <td>Expenses</td>
            <td colspan="2" class="danger">-{{ teoBudget.expenses}}</td>
        </tr>
        {% for expensesItem in teoBudget.detailExpenses %}
            <tr>
                <td><p class="text-right p-0 m-0">{{ expensesItem.description }}</p></td>
                <td colspan="2">
                    {% if expensesItem.multi != 1 %}
                        <span class="c-warning">-{{ expensesItem.amount }}</span>
                        <span class="c-warning">x{{ expensesItem.multi }}</span>
                        =
                    {% endif %}
                    <span class="c-danger">-{{ expensesItem.result }}</span>
                </td>
            </tr>
        {% endfor %}
        <tr>
            <td>Free money</td>
            <td class="success" colspan="2">{{ teoBudget.freeMoney }}</td>
        </tr>
    </tbody>
</table>